### ISSUE TITLE
Received ack did not match expected ack

### ISSUE THREAD

**Issue by rcdailey** [bezmi/hass_custom_components#25]
This error originated from a custom integration.

Logger: custom_components.jvc_projectors.remote
Source: custom_components/jvc_projectors/remote.py:137
Integration: jvc_projectors
First occurred: 3:52:06 AM (54 occurrences)
Last logged: 10:01:23 AM

Received ack did not match expected ack: b'\x06\x89\x01PW\n@\x89\x01PW0\n' != b'\x06\x89\x01PW\n'
Connecting failed, retrying in 2 seconds

**Comment by rcdailey** [comment]
I'm using an NZ7 projector on the V2.0 firmware

**Comment by bezmi** [comment]
Hi, is the projector still functioning to an acceptable level even with this error? I am hoping to iron out most of the non-critical communication bugs in the next update.

**Comment by bezmi** [comment]
I will need to look up the changes made in v2.0 projector firmware. It looks like this may have changed things for the latest models.

**Comment by rcdailey** [comment]
I'm not sure if this is related, but I also see this in the logs. If I need to open another issue just let me know. Thanks and I apologize for being unresponsive on this one.

```
2023-01-22 05:01:56.252 ERROR (SyncWorker_25) [custom_components.jvc_projectors.remote] Connection timed out. Command b'?\x89\x01PW\n' may not be allowed to run at this time or something else is running already.
2023-01-22 05:01:56.253 WARNING (SyncWorker_25) [custom_components.jvc_projectors.remote] Connecting failed, retrying in 2 seconds
2023-01-22 05:01:58.379 ERROR (MainThread) [homeassistant.helpers.entity] Update for remote.jvc_projector fails
```

**Comment by bezmi** [comment]
Can you please confirm which version of the home assistant component you are on? Those latest error messages do not look familiar.

Edit: neither does the error message from your first comment. The custom component is called "jvcprojector" not "jvc_projectors". Please confirm that you are using this component and not someone else's.

**Comment by rcdailey** [comment]
I am seriously so sorry; I'm an idiot. This whole time I was posting on the wrong project 😢 

I meant to post here: https://github.com/iloveicedgreentea/jvc_homeassistant

Again I am sorry for wasting your time! I will close this issue.
